In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('..\\dataset\\ecommerce_sales_analytics_5000.csv')

In [8]:
df.sample(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
152,10153,6/2/2022,1040,Home,West,1,409.55,0.32,Card,9,4.6,278.49
341,10342,12/8/2022,1819,Electronics,West,5,36.39,0.27,Card,1,4.1,132.82
1855,11856,1/30/2027,1454,Electronics,West,1,291.17,0.01,COD,5,4.4,288.26
534,10535,6/19/2023,1902,Clothing,North,3,363.76,0.20,Wallet,6,1.9,873.02
3930,13931,10/5/2032,1638,Home,West,2,402.56,0.23,Wallet,6,2.9,619.94
4822,14823,3/16/2035,1475,Electronics,West,1,192.61,0.30,Card,6,2.5,134.83
3860,13861,7/27/2032,1916,Clothing,North,6,546.35,0.18,Wallet,4,3.3,2688.04
3637,13638,12/17/2031,1780,Electronics,North,2,568.87,0.15,COD,10,1.5,967.08
4958,14959,7/30/2035,1413,Clothing,West,4,353.47,0.23,Card,11,4.5,1088.69
3136,13137,8/3/2030,1229,Electronics,South,6,458.15,0.16,Card,11,4.3,2309.08

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 468.9 KB

In [17]:
df[df.duplicated()]  # 0 row
# df[df['order_id'].duplicated()] # 0 row

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_category, region, quantity, unit_price, discount, payment_method, delivery_days, customer_rating, revenue]
Index: []

In [12]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(4), str(3)
memory usage: 468.9 KB

In [22]:
df['month'] = df['order_date'].dt.month

In [23]:
df['year_quarter'] = df['order_date'].dt.to_period('Q')

In [27]:
df['year'] = df['order_date'].dt.year

In [28]:
# df.info()
df.sample(2)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,month,year_quarter,year
821,10822,2024-04-01,1934,Electronics,South,7,110.73,0.32,Card,3,4.7,527.07,4,2024Q2,2024
4122,14123,2033-04-15,1965,Electronics,East,5,358.84,0.20,Wallet,6,2.3,1435.36,4,2033Q2,2033