In [46]:
import pandas as pd
import plotly.express as px

In [47]:
df = pd.read_csv('..\\dataset\\ecommerce_sales_analytics_5000.csv')

## data analysis

In [48]:
df.sample(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4501,14502,4/29/2034,1396,Clothing,East,7,327.99,0.20,Card,4,4.9,1836.74
4821,14822,3/15/2035,1486,Clothing,East,4,210.16,0.00,Card,2,1.1,840.64
3410,13411,5/4/2031,1900,Clothing,North,7,18.80,0.32,COD,9,1.3,89.49
2937,12938,1/16/2030,1042,Clothing,South,4,149.92,0.32,Card,5,2.5,407.78
3210,13211,10/16/2030,1499,Electronics,North,5,237.63,0.28,Card,9,4.7,855.47
388,10389,1/24/2023,1627,Beauty,West,6,385.77,0.23,Card,9,4.3,1782.26
1594,11595,5/14/2026,1968,Clothing,South,2,457.94,0.09,COD,11,4.2,833.45
493,10494,5/9/2023,1322,Clothing,East,7,86.11,0.17,Card,10,4.1,500.30
4920,14921,6/22/2035,1018,Home,South,1,266.11,0.07,Card,2,3.1,247.48
2414,12415,8/11/2028,1059,Home,South,5,563.30,0.23,COD,11,4.7,2168.70

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 468.9 KB

In [50]:
df[df.duplicated()]  # 0 row
# df[df['order_id'].duplicated()] # 0 row

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_category, region, quantity, unit_price, discount, payment_method, delivery_days, customer_rating, revenue]
Index: []

In [51]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [52]:
df['month'] = df['order_date'].dt.month_name()

In [68]:
df['year_quarter'] = df['order_date'].dt.quarter

In [54]:
df['year'] = df['order_date'].dt.year

In [62]:
df['product_category'] = df['product_category'].astype(str).str.strip()
df['region'] = df['region'].astype(str).str.strip()
df['payment_method'] = df['payment_method'].astype(str).str.strip()

In [56]:
df = df[df['quantity']>0]

In [57]:
df = df[df['delivery_days'] > 0]

In [69]:
df.info()
# df.sample(2)

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
 12  month             5000 non-null   str
 13  year_quarter      5000 non-null   int32
 14  year              5000 non-null   int32
dtypes: datetime64[us](1), float64(4), int32(2), int64(4), str(4)
memory usage: 547.0 KB

In [64]:
df.groupby('year').agg({'revenue':'sum', 'quantity':'sum'}).sort_values(by=['revenue'], ascending=False)

        revenue  quantity
year
2033  408725.72      1524
2030  387884.46      1500
2032  386584.63      1492
2026  386369.69      1478
2027  386151.91      1546
2028  376844.80      1476
2022  371824.30      1469
2023  365915.79      1497
2031  365250.83      1427
2034  363239.55      1431
2024  363209.13      1489
2029  359239.24      1472
2025  349802.33      1410
2035  238733.36      1013

In [66]:
df.groupby('month').agg({'revenue':'sum', 'quantity':'sum'}).sort_values(by=['revenue'], ascending=False)

             revenue  quantity
month
May        479772.55      1835
August     460874.78      1738
June       442941.58      1752
July       440570.72      1750
January    426374.92      1772
March      425050.52      1750
February   413890.24      1571
November   410657.88      1629
October    407873.12      1642
September  402368.11      1591
December   400686.16      1539
April      398715.16      1655

In [70]:
df.groupby('year_quarter').agg({'revenue':'sum', 'quantity':'sum'}).sort_values(by=['revenue'], ascending=False)

                 revenue  quantity
year_quarter
2             1321429.29      5242
3             1303813.61      5079
1             1265315.68      5093
4             1219217.16      4810

In [74]:
df.groupby('customer_id').agg({'order_id':'count'}).sort_values(by=['order_id'], ascending=False)

             order_id
customer_id
1663               14
1957               12
1928               12
1935               12
1112               12
...               ...
1023                1
1978                1
1005                1
1964                1
1999                1

[989 rows x 1 columns]

In [76]:
df.groupby('customer_id').agg({'revenue':'sum'}).sort_values(by=['revenue'], ascending=False)

              revenue
customer_id
1663         17680.69
1955         16265.15
1675         15036.46
1276         15023.71
1647         14894.97
...               ...
1715           255.12
1350           254.25
1809           231.68
1109           172.33
1705           119.06

[989 rows x 1 columns]